### ISSUE TITLE
kerberos support

### ISSUE THREAD

**Issue by JensTimmerman** [waldur/python-freeipa#2]
It seems that currently this python-freeipa client needs a username/password combo to connect to the api.
Using https://github.com/requests/requests-kerberos you can enable kerberos support in the python requests library.
see https://gist.github.com/JensTimmerman/c123d5f6291e4cd542473241ce7bf4c9 for a working example of using kerberos with the freeipa api and python-requests.

**Comment by JensTimmerman** [comment]
actually, https://pypi.python.org/pypi/requests-gssapi should probably be used.

**Comment by AmbientLighter** [comment]
@JensTimmerman Sorry for the late reply and thank you for the link to this gist. PR would be highly appreciated. However, I think that it makes sense to make requests_kerberos dependency optional, so that it wouldn't be required until it's actually used. Also I think that it makes sense to keep current issue open so that this gist would be useful until kerberos support is implemented in python-freeipa library too.
