### ISSUE TITLE
No ability to provide any functions with kwargs

### ISSUE THREAD

**Issue by james02135** [waldur/python-freeipa#38]
From releases prior to 1.0.0, there was the ability to provide functions with kwargs, but since that upgrade, there are no longer any kwargs in the generated client. It seems to me that the object at https://github.com/opennode/python-freeipa/blob/develop/contrib/py_ipa_api_recreate#L348 is malformed from what was expected.

**Comment by schlitzered** [comment]
why should the generated methods accept **kwargs?

the ClientMeta class is generated by the freeipa API JSON API spec.

the generated methods, contain all known options and arguments that are specified by the API for this method.

can you maybe provide a use case/example code, of what you are trying to archive?

**Comment by StephenCoady** [comment]
Hi @schlitzered. Sure! 

We are working with an extended FreeIPA server which has a modified schema. In this case, we would need to either generate the client ourselves (and therefore also track upstream with this manually generated client) or we need to be able to provide key-worded args to the ClientMeta class. In the beta version certain methods accepted kwargs. I feel like since it is possible to extend FreeIPA's schema like we have done then it would make sense to also be able to use python-freeipa to interact with _any_ FreeIPA server and not just the standard one.

You can see the plugin in question [here](https://github.com/fedora-infra/freeipa-fas).

**Comment by schlitzered** [comment]
interesting.

IMHO, i would simply recreate the client, using the API specs that is generated by the IPA server you are running. 

also, i cannot remember that the MetaClient ever accepted **kwargs, only ClientLegacy is doing this.

**Comment by StephenCoady** [comment]
@schlitzered but that makes tracking your library much more difficult and time consuming. we would have a working client, sure, but we would need to run that generation for every fix/feature upstream. Thats not to mention any API spec changes.

Whereas if we add kwargs we only need to change once and then python-freeipa supports all IPA servers. In my opinion this is a much better solution for us _and_ python-freeipa.

> also, i cannot remember that the MetaClient ever accepted **kwargs, only ClientLegacy is doing this.

Yes true, by beta I meant pre-1.0.0 so the old client.

**Comment by livenson** [comment]
My 5 cents - I think indeed supporting kwargs would increase hackability of the library and make it fit better for the cases that @StephenCoady described.

**Comment by StephenCoady** [comment]
I notice there is some mention of kwargs in the code [here](https://github.com/opennode/python-freeipa/blob/develop/contrib/py_ipa_api_recreate#L350) but I'm not sure it works or maybe the spec never returns the object type the code is looking for. Either way, I think if the goal is to make python-freeipa as flexible as possible then all functions should probably accept kwargs as this has very little downsides that I can think of. WDYT?

If so, the fix is simple and we could have a PR open today.

**Comment by livenson** [comment]
@schlitzered , do you have any strong opinion against this?

**Comment by schlitzered** [comment]
@StephenCoady: the line you are mentioning has been added because of a method, that had a strange argspec, and acutally this seems to be a bug, which i reported upstream already.

@livenson: it is not a strong opinion. this can sure be added, the change is trivial. it is just that i personally would recreate the api to match my use case.

**Comment by livenson** [comment]
Ok, @StephenCoady , you are welcome to submit a PR!
